<!-- Can you create your own exception class ?
Write a sample code to throw the above exception using throw keyword. -->